import Head from 'next/head'
import { useEffect, useState } from 'react'
import { useSelector, useDispatch } from 'react-redux'

import { MainLayout } from '@/components/layout'
import HeadlineTag from '@/components/HeadlineTag'
import Post from '@/components/blog/Post'
import FadeUpAnimation from '@/components/common/FadeUpAnimation'
import { getListPosts, selectListPosts, selectHighlightPosts } from '@/store/postSlice'
import { getListCategories, selectListCategories } from '@/store/categorySlice'
import { ROUTES, CATEGORY_TYPE } from '@/constants'


export default function BlogPage() {
  const dispatch = useDispatch()
  const posts = useSelector(selectListPosts)
  const highlightPosts = useSelector(selectHighlightPosts)
  const categoryList = useSelector(selectListCategories)
  const [categoryNameFilter, setCategoryNameFilter] = useState('')

  const handleClickCategory =(cat) => {
    dispatch(getListPosts({ limit: 4, category_slug: cat?.slug, published: true }))
    setCategoryNameFilter(cat?.name)
  }

  useEffect(() => {
    dispatch(getListCategories({ type: CATEGORY_TYPE.POST }))
    Promise.all([
      dispatch(getListPosts({ limit: 4, published: true })),
      dispatch(getListPosts({ limit: 2, highlight: true, published: true }))
    ])
  }, [])

  return (
    <>
      <Head>
        <title>Our Blogs</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <MainLayout>
        <FadeUpAnimation>
          <section className='py-25 px-4'>
            <div className='ct-container mx-auto'>
              <h1 className='text-4xl text-secondary text-center'>Read coffee stories on our Blog</h1>
              <h4 className='text-lg mt-4 mb-10 text-center max-w-140 mx-auto'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique.</h4>
            </div>
          </section>
        </FadeUpAnimation>

        <FadeUpAnimation>
          <section className='px-4 pb-25'>
            <div className='ct-container mx-auto'>
              <HeadlineTag title='Hightlight post' />
              <div className='grid grid-cols-1 gap-4 sm:grid-cols-2'>
                {
                  highlightPosts.map((post) =>
                    <Post
                      key={post?._id}
                      title={post?.title}
                      description={post?.description}
                      date={post?.createdAt}
                      thumb={post?.thumbnail?.url}
                      url={ROUTES.BLOG_DETAIL_PAGE.replace(':slug', post?.slug)}
                    />
                  )
                }
              </div>
            </div>
          </section>
        </FadeUpAnimation>

        <section className='px-4 pb-25'>
          <div className='ct-container mx-auto'>
            <div className='grid grid-cols-1 lg:grid-cols-[6fr_4fr] xl:grid-cols-[7fr_3fr] gap-4'>
              {/* Lastes post  */}
              <div>
                <h3 className='text-secondary text-2xl border-b border-b-[#ececed] pb-6 mb-6'>Latest Posts</h3>
                { posts.length === 0 && <p>No post belong to <b>&quot;{categoryNameFilter}&quot;</b> category</p> }
                <div className='grid grid-cols-1 gap-4 sm:grid-cols-2'>
                  {
                    posts.map((post) =>
                      <Post
                        key={post?._id}
                        title={post?.title}
                        description={post?.description}
                        date={post?.createdAt}
                        thumb={post?.thumbnail?.url}
                        url={ROUTES.BLOG_DETAIL_PAGE.replace(':slug', post?.slug)}
                      />
                    )
                  }
                </div>
              </div>

              {/* Sidebar post  */}
              <FadeUpAnimation>
                <div>
                  <h3 className='text-secondary text-2xl border-b border-b-[#ececed] pb-6 mb-6'>Categories</h3>
                  <ul>
                    <li className='cursor-pointer' onClick={() => dispatch(getListPosts({ limit: 4, published: true }))}><span className='ct-category-item'>All</span></li>
                    {
                      categoryList.map((cat) => <li key={cat?._id} className='cursor-pointer' onClick={() => handleClickCategory(cat)}><span className='ct-category-item' href='#'>{cat?.name}</span></li>)
                    }
                  </ul>
                </div>
              </FadeUpAnimation>

            </div>
          </div>
        </section>

        <FadeUpAnimation>
          <section className='px-4 pb-25'>
            <div className='ct-container mx-auto'>
              <p className='text-light-coffee text-xl text-center border-l border-b border-light-coffee/50 p-4 sm:p-9'>&quot;I wake up some mornings and sit and have my coffee and look out at my beautiful garden, and I go, ’Remember how good this is. Because you can lose it.&quot;</p>
              <p className='text-center font-bold mt-6'>Jason Johnson - Owner of CoffeeStyle</p>
            </div>
          </section>
        </FadeUpAnimation>
      </MainLayout>
    </>
  )
}