import { useEffect } from 'react'
import Head from 'next/head'
import { useSelector, useDispatch } from 'react-redux'
import { useRouter } from 'next/router'

import { getPostDetailBySlug, selectPostDetail } from '@/store/postSlice'
import { MainLayout } from '@/components/layout'
import FadeUpAnimation from '@/components/common/FadeUpAnimation'

const BlogAdmin = () => {
  const dispatch = useDispatch()
  const post = useSelector(selectPostDetail)
  const router = useRouter()
  const { slug } = router.query

  useEffect(() => {
    dispatch(getPostDetailBySlug({ slug }))
  }, [dispatch, slug])

  return (
    <>
      <Head>
        <title>{post?.title}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <MainLayout>
        <FadeUpAnimation>
          <section className='px-4 py-25 ct-container mx-auto'>
            <h1 className='mb-6 text-4xl font-bold'>
              {post?.title}
            </h1>

            <article
              className='prose max-w-none'
              dangerouslySetInnerHTML={{
                __html: post?.content
              }}
            />
          </section>
        </FadeUpAnimation>
      </MainLayout>
    </>
  )
}

export default BlogAdmin