import React from 'react'
import Head from 'next/head'
import { CiEdit } from 'react-icons/ci'
import { FaTrash } from 'react-icons/fa6'
import { useDispatch, useSelector } from 'react-redux'
import { useEffect, useState } from 'react'
import { toast } from 'react-toastify'
import clsx from 'clsx'
import Link from 'next/link'
import { useRouter } from 'next/router'

import { AdminLayout } from '@/components/layout'
import Pagination from '@/components/common/Pagination'
import Button from '@/components/common/Button'
import { getListPosts, selectListPosts } from '@/store/postSlice'
import { openModal } from '@/store/modalSlice'
import { deletePostById } from '@/store/postSlice'
import { datetimeHelpers } from '@/helpers'
import { ADMIN_ROUTES } from '@/constants'


const ListPostPage = () => {
  const dispatch = useDispatch()
  const posts = useSelector(selectListPosts)
  const pagination = useSelector(state => state.promotion.pagination)
  const [page, setPage] = useState(1)

  const router = useRouter()

  const handleEdit = (postId) => {
    router.push(
      ADMIN_ROUTES.UPDATE_POST_PAGE.replace(':id', postId)
    )
  }

  const handleDelete = (post) => {
    dispatch(
      openModal({
        type: 'CONFIRM',
        name: 'CONFIRM_MODAL',
        data: post,
        props: {
          title: 'Delete post',
          content: () => (
            <>
                You want to delete post <b>{post.title}</b> ?
            </>
          ),
          confirmText: 'Delete',
          onConfirm: async (post) => {
            try {
              await dispatch(
                deletePostById({ postId: post?._id })
              ).unwrap()
              toast.success('Delete post successfully')
            } catch (error) {
              toast.error('Delete failed')
            }
          }
        }
      })
    )
  }

  useEffect(() => {
    dispatch(getListPosts())
  }, [])

  return (
    <>
      <Head>
        <title>Admin - List Posts</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <AdminLayout>
        <section>
          <h1 className='text-3xl font-bold mb-5'>List Posts</h1>
          <div className='bg-white rounded-lg shadow overflow-hidden'>
            <table className='w-full text-sm text-left'>
              <thead className='bg-gray-100 text-gray-600 uppercase text-xs'>
                <tr>
                  <th className='px-4 py-3'>#</th>
                  <th className='px-4 py-3'>Title</th>
                  <th className='px-4 py-3'>Description</th>
                  <th className='px-4 py-3'>Category</th>
                  <th className='px-4 py-3'>Slug</th>
                  <th className='px-4 py-3'>Highlight</th>
                  <th className='px-4 py-3'>Published</th>
                  <th className='px-4 py-3'>Create At</th>
                  <th className='px-4 py-3'>Action</th>
                </tr>
              </thead>
              <tbody>
                { posts.length === 0 && (
                  <tr>
                    <td colSpan={11} className='p-4 font-bold'>Empty post</td>
                  </tr>
                ) }
                {
                  posts && posts.map((post, index) => (
                    <tr key={index} className='border-b hover:bg-gray-200'>
                      <td className='px-4 py-3 font-medium'>{index + 1}</td>
                      <td className='px-4 py-3 font-medium'>{post?.title}</td>
                      <td className='px-4 py-3 font-medium'>{post?.description}</td>
                      <td className='px-4 py-3 font-medium'>{post?.category?.name}</td>
                      <td className='px-4 py-3 font-medium'>{post?.slug}</td>
                      <td className='px-4 py-3 font-medium'><span className={clsx(post?.highlight ? 'bg-green-100 text-green-700 font-bold px-2 rounded-lg' : '')}>{post?.highlight ? 'Highlight' : 'No'}</span></td>
                      <td className='px-4 py-3 font-medium'><span className={clsx(post?.published ? 'bg-green-100 text-green-700 font-bold px-2 rounded-lg' : '')}>{post?.published ? 'Yes' : 'No'}</span></td>
                      <td className='px-4 py-3 font-medium'>{datetimeHelpers.formatDate(post?.createdAt, 'en')}</td>
                      <td className='px-4 py-3 flex items-center gap-4'>
                        <CiEdit size={20} className='cursor-pointer transition-all hover:scale-[1.2]' onClick={() => handleEdit(post?._id)} />
                        <FaTrash size={20} className='cursor-pointer transition-all hover:scale-[1.2]' onClick={() => handleDelete(post)} />
                      </td>
                    </tr>
                  ))
                }
              </tbody>
            </table>
          </div>

          <Pagination
            currentPage={page}
            totalPages={pagination.totalPages}
            onPageChange={setPage}
          />

          <div className='text-right mt-6'>
            <Link href={ADMIN_ROUTES.CREATE_POST_PAGE}>
              <Button size='sm' variant='secondary'>Create post</Button>
            </Link>
          </div>

        </section>
      </AdminLayout>
    </>
  )
}

export default ListPostPage