import Head from 'next/head'
import { useDispatch, useSelector } from 'react-redux'
import { useEffect } from 'react'
import Link from 'next/link'
import Image from 'next/image'

import Button from '@/components/common/Button'
import Post from '@/components/blog/Post'
import FadeUpAnimation from '@/components/common/FadeUpAnimation'
import Product from '@/components/product/Product'
import HeadlineTag from '@/components/HeadlineTag'
import { MainLayout } from '@/components/layout'
import { ROUTES, STATUS } from '@/constants'
import { getListProducts, selectListProducts, selectHighlightProducts } from '@/store/productSlice'

export default function Home() {
  const dispatch = useDispatch()
  const listProducts = useSelector(selectListProducts)
  const listHighlightProducts = useSelector(selectHighlightProducts)

  useEffect(() => {
    Promise.all([
      dispatch(getListProducts({ limit: 6, status: STATUS.ACTIVE })),
      dispatch(getListProducts({ limit: 2, highlight: true, status: STATUS.ACTIVE }))
    ])
  }, [])

  return (
    <>
      <Head>
        <title>Coffee Shop</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <MainLayout>
        {/* Banner  */}
        <FadeUpAnimation>
          <section className="px-4 h-132.5 flex justify-center items-center relative bg-[url('/images/banner-homepage.jpg')] bg-cover bg-no-repeat bg-bottom after:bg-black after:opacity-40 after:h-full after:w-full after:absolute after:z-10">
            <div className='text-center text-white relative z-20'>
              <h3 className='text-sm opacity-90 uppercase font-bold'>Best place to buy design 123</h3>
              <h1 className='text-5xl my-3'>Coffee Mugs abc</h1>
              <h6 className='text-lg mb-8 opacity-90'>The most versatile furniture system ever created. Designed to fit your life, made to move and grow.</h6>
              <Link href={ROUTES.PRODUCTS_PAGE}><Button variant='outline' size='lg' className='hover:bg-light-coffee hover:text-white hover:border-light-coffee font-bold'>Explore Our Products</Button></Link>
            </div>
          </section>
        </FadeUpAnimation>

        {/* Story  */}
        <FadeUpAnimation>
          <section className='text-center py-25 px-4'>
            <div className='max-w-175 mx-auto'>
              <h2 className='text-3xl text-title'>Even the all-powerful Pointing has no control about the blind texts.</h2>
              <p className='py-5'>It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
              <Link href={ROUTES.BLOG_PAGE} className='text-light-coffee border-b-2 border-light-coffee/50 pb-1'>Read the full Story</Link>
            </div>
          </section>
        </FadeUpAnimation>

        {/* Hightlight  */}
        {
          listHighlightProducts.length > 0 &&
          <FadeUpAnimation>
            <section className='px-4 pb-25'>
              <div className='ct-container mx-auto'>
                <HeadlineTag title='Highlight products' />
                <div className='grid grid-cols-1 gap-6 sm:grid-cols-2 sm:gap-6'>
                  {
                    listHighlightProducts.map((product, index) =>
                      <Product
                        key={index}
                        name={product.name}
                        images={product.images}
                        originPrice={product.origin_price}
                        promotionPrice={product.promotion_price}
                        isOnSale={product.on_sale}
                        url={ROUTES.PRODUCTS_DETAIL_PAGE.replace(':slug', product.slug)}
                      />)
                  }
                </div>
              </div>
            </section>
          </FadeUpAnimation>
        }

        {/* Product  */}
        {
          listProducts.length > 0 &&
          <section className='px-4'>
            <div className='ct-container mx-auto'>
              <HeadlineTag title='More Products' />
              <div className='grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 sm:gap-6'>
                {
                  listProducts.map((product) =>
                    <Product
                      key={product._id}
                      name={product.name}
                      images={product.images}
                      originPrice={product.origin_price}
                      promotionPrice={product.promotion_price}
                      isOnSale={product.on_sale}
                      url={ROUTES.PRODUCTS_DETAIL_PAGE.replace(':slug', product.slug)}
                    />)
                }
              </div>
            </div>
          </section>
        }

        {/* Magazine  */}
        <FadeUpAnimation>
          <section className='px-4 py-15'>
            <div className='max-w-235 mx-auto'>
              <HeadlineTag title='Get a coffee magazine free' />
              <div className='sm:grid sm:grid-cols-2 sm:gap-4'>
                <div className='mb-4'>
                  <div className='mt-6 uppercase font-bold text-xs'>Premium Offer</div>
                  <h2 className='mt-3 mb-4 text-secondary text-4xl'>Get our Coffee Magazine</h2>
                  <p className='mb-4 max-w-100'>The most versatile furniture system ever created. Designed to fit your life.</p>
                  <Link href={ROUTES.PRODUCTS_PAGE}><Button variant='secondary'>START SHOPPING</Button></Link>
                </div>
                <div className='lg:grid lg:grid-cols-5 lg:gap-4'>
                  <div className='h-70 relative mb-4 lg:w-70 lg:col-span-3 lg:mb-0'><Image className='object-cover object-center w-full h-full' src='/images/magazine-1.jpg' fill sizes='(max-width: 1024px) 50vw, 100vw' alt='image' /></div>
                  <div className='grid grid-cols-2 gap-4 w-full h-32.5 lg:grid-cols-1 lg:h-70 lg:col-span-2'>
                    <div className='relative'><Image className='object-cover object-center' src='/images/magazine-2.jpg' fill sizes='(max-width: 1024px) 50vw, 100vw' alt='image' /></div>
                    <div className='relative'><Image className='object-cover object-center' src='/images/magazine-3.jpg' fill sizes='(max-width: 1024px) 50vw, 100vw' alt='image' /></div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </FadeUpAnimation>

        {/* Parallax  */}
        <FadeUpAnimation><section className="bg-[url('/images/bg-parallax.jpg')] bg-cover bg-no-repeat bg-center h-85 bg-fixed"></section></FadeUpAnimation>

        {/* Blog  */}
        <FadeUpAnimation>
          <section className='px-4 py-25'>
            <div className='ct-container mx-auto'>
              <HeadlineTag title='Behind the mugs, lifestyle stories' />
              <div className='grid grid-cols-1 gap-6 sm:grid-cols-2 xl:grid-cols-4'>
                <Post title='Health Check: why do I get a headache when I have not had my coffee?' description='It is a paradisematic country, in which roasted parts of sentences fly into your mouth.' date='October 9, 2018' thumb='/images/blogs/blog-1.jpg' />
                <Post title='How long does a cup of coffee keep you awake?' description='It is a paradisematic country, in which roasted parts. Vel qui et ad voluptatem.' date='October 9, 2018' thumb='/images/blogs/blog-2.jpg' />
                <Post title='Recent research suggests that heavy coffee drinkers may reap health benefits. ' description='It is a paradisematic country, in which roasted parts of sentences fly into your mouth.' date='October 9, 2018' thumb='/images/blogs/blog-3.jpg' />
                <Post title='Health Check: why do I get a headache when I have not had my coffee?' description='It is a paradisematic country, in which roasted parts of sentences fly into your mouth.' date='October 9, 2018' thumb='/images/blogs/blog-1.jpg' />
              </div>
            </div>
          </section>
        </FadeUpAnimation>

      </MainLayout>
    </>
  )
}