import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import clsx from 'clsx'
import { useDispatch, useSelector } from 'react-redux'

import { getListProducts, selectListProducts } from '@/store/productSlice'
import { getListCategories, selectListCategories } from '@/store/categorySlice'
import { ROUTES, CATEGORY_TYPE, STATUS } from '@/constants'
import Pagination from '@/components/common/Pagination'
import { MainLayout } from '@/components/layout'
import Product from '@/components/product/Product'


export default function ProductPage() {
  const LIMIT = 6
  const [category, setCategory] = useState('all')
  const dispatch = useDispatch()
  const listProducts = useSelector(selectListProducts)
  const activeProducts = listProducts.filter(product => product.status === STATUS.ACTIVE)
  const listCategories = useSelector(selectListCategories)
  const pagination = useSelector(state => state.product.pagination)
  const [page, setPage] = useState(1)

  const handleFilter = (slug) => {
    setCategory(slug)
  }

  useEffect(() => {
    dispatch(getListProducts({ limit: LIMIT }))
    dispatch(getListCategories({ type: CATEGORY_TYPE.PRODUCT }))
  }, [])

  useEffect(() => {
    if (category === 'all') {
      dispatch(getListProducts({ limit: LIMIT }))
    } else {
      dispatch(getListProducts({ category_slug: category, limit: LIMIT }))
    }
  }, [category])

  useEffect(() => {
    if (category === 'all') {
      dispatch(getListProducts({ limit: LIMIT, page }))
    } else {
      dispatch(getListProducts({ limit: LIMIT, page, category_slug: category }))
    }
  }, [page])

  return (
    <>
      <Head>
        <title>Our Products</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <MainLayout>
        <section className='py-25 px-4'>
          <div className='ct-container mx-auto'>
            <h1 className='text-4xl text-secondary text-center'>Our Products</h1>
            <h4 className='text-lg mt-4 mb-10 text-center'>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h4>
            <div className='sm:flex justify-center mb-6'>
              <button
                className={clsx({
                  'ct-button ct-btn-filter': true,
                  'bg-light-coffee text-white!': category == 'all'
                })}
                onClick={() => setCategory('all')}
              >
                All products
              </button>
              {
                listCategories.map((cat) =>
                  <button
                    key={cat?._id}
                    onClick={() => handleFilter(cat?.slug)}
                    className={clsx({
                      'ct-button ct-btn-filter': true,
                      'bg-light-coffee text-white!': category == cat?.slug
                    })}
                  >
                    {cat?.name}
                  </button>
                )
              }
            </div>
            {
              activeProducts.length > 0
                ? (
                  <div className='grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 sm:gap-6'>
                    {
                      activeProducts.map((product) => (
                        <Product
                          key={product._id}
                          name={product.name}
                          images={product.images}
                          originPrice={product.origin_price}
                          promotionPrice={product.promotion_price}
                          isOnSale={product.on_sale}
                          url={ROUTES.PRODUCTS_DETAIL_PAGE.replace(':slug', product.slug)}
                        />
                      ))
                    }
                  </div>
                )
                : (
                  <p className='text-center font-bold capitalize'>Empty product</p>
                )
            }

            <Pagination
              currentPage={page}
              totalPages={pagination.totalPages}
              onPageChange={setPage}
            />

          </div>
        </section>
      </MainLayout>
    </>
  )
}