import React, { useEffect } from 'react'
import { FaArrowUpLong } from 'react-icons/fa6'
import Link from 'next/link'
import Image from 'next/image'
import Head from 'next/head'
import { useDispatch, useSelector } from 'react-redux'

import { AdminLayout } from '@/components/layout'
import LineChart from '@/components/admin/chart/LineChart'
import { getListOrders, GET_LIST_ORDERS, selectListOrders } from '@/store/orderSlice'
import { getListPosts, GET_LIST_POSTS, selectListPosts } from '@/store/postSlice'
import { getBestSellingProducts, GET_BEST_SELLING_PRODUCTS, selectBestSellingProducts } from '@/store/productSlice'
import { ADMIN_ROUTES, ROUTES } from '@/constants'
import { datetimeHelpers } from '@/helpers'

const DashboardPage = () => {
  const dispatch = useDispatch()
  const orders = useSelector(selectListOrders)
  const posts = useSelector(selectListPosts)
  const bestSellingProducts = useSelector(selectBestSellingProducts)

  useEffect(() => {
    dispatch(getListOrders({ limit: 5 }))
    dispatch(getListPosts({ limit: 3 }))
    dispatch(getBestSellingProducts())
  }, [])

  return (
    <>
      <Head>
        <title>Admin - Dashboard</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <AdminLayout>
        <section>
          <h1 className='text-3xl font-bold'>Dashboard</h1>
          <h4 className='text-primary mb-4'>Overview of store operations</h4>
          <div className='grid grid-cols-4 gap-x-4'>
            <div className='bg-white text-secondary p-4 rounded-lg'>
              <h6 className='font-bold'>Total revenue</h6>
              <div className='font-bold text-2xl my-2'>128.254.000 Đ</div>
              <div className='text-primary flex items-center text-md'><span className='text-green-500 flex items-center mr-2 font-bold'><FaArrowUpLong />12.5%</span> previous month</div>
            </div>
            <div className='bg-white text-secondary p-4 rounded-lg'>
              <h6 className='font-bold'>Total orders</h6>
              <div className='font-bold text-2xl my-2'>635</div>
              <div className='text-primary flex items-center text-md'><span className='text-green-500 flex items-center mr-2 font-bold'><FaArrowUpLong />8.5%</span> previous month</div>
            </div>
            <div className='bg-white text-secondary p-4 rounded-lg'>
              <h6 className='font-bold'>Total new clients</h6>
              <div className='font-bold text-2xl my-2'>128</div>
              <div className='text-primary flex items-center text-md'><span className='text-green-500 flex items-center mr-2 font-bold'><FaArrowUpLong />5%</span> previous month</div>
            </div>
            <div className='bg-white text-secondary p-4 rounded-lg'>
              <h6 className='font-bold'>Total products</h6>
              <div className='font-bold text-2xl my-2'>540</div>
              <div className='text-primary flex items-center text-md'><span className='text-green-500 flex items-center mr-2 font-bold'><FaArrowUpLong />12%</span> previous month</div>
            </div>
          </div>
        </section>

        <section className='grid grid-cols-[3fr_2fr] gap-4 mt-10'>
          <div className='bg-white p-4 rounded-lg'><LineChart /></div>
          <div className='bg-white px-4 rounded-lg'>
            <div className='flex justify-between items-center border-b border-primary/50 py-4'>
              <h3 className='text-secondary text-lg font-bold'>Newest orders</h3>
              <Link href={ADMIN_ROUTES.ORDER_ADMIN_PAGE} className='text-blue-500'>View all</Link>
            </div>
            <ul className='py-2'>
              {
                orders.map((order, index) => (
                  <li className='grid grid-cols-[2fr_2fr_1fr] py-2' key={index}>
                    <span className='font-bold text-secondary'>#ORD{order?._id.slice(-4).toUpperCase()}</span>
                    <span>{datetimeHelpers.formatDate(order?.createdAt)}</span>
                    <span className='text-right font-bold text-secondary'>{order?.final_total} USD</span>
                  </li>
                ))
              }
            </ul>
          </div>
        </section>

        <section className='grid grid-cols-[3fr_2fr] gap-4 mt-4'>
          <div className='bg-white px-4 rounded-lg'>
            <div className='flex justify-between items-center border-b border-primary/50 py-4'>
              <h3 className='text-secondary text-lg font-bold'>Best selling</h3>
              <Link href={ADMIN_ROUTES.PRODUCT_ADMIN_PAGE} className='text-blue-500'>View all</Link>
            </div>
            <ul className='py-2'>
              {
                bestSellingProducts.map((product, index) => (
                  <li className='grid grid-cols-[4fr_1fr] py-2' key={index}>
                    <div className='flex items-center'>
                      <Image src={product?.image} width={60} height={60} className='rounded-full' alt={product?.name} />
                      <span className='font-bold text-secondary ml-4'>{product?.name}</span>
                    </div>
                    <span className='font-bold text-secondary flex items-center justify-end'>{product?.total_sold} items</span>
                  </li>
                ))
              }
            </ul>
          </div>
          <div className='bg-white px-4 rounded-lg'>
            <div className='flex justify-between items-center border-b border-primary/50 py-4'>
              <h3 className='text-secondary text-lg font-bold'>Newest post</h3>
              <Link href={ADMIN_ROUTES.LIST_POST_PAGE} className='text-blue-500'>View all</Link>
            </div>
            <ul className='py-2'>
              {
                posts.map((post, index) => (
                  <li className='grid grid-cols-[4fr_1fr] py-2' key={index}>
                    <Link href={ROUTES.BLOG_DETAIL_PAGE.replace(':slug', post?.slug)} className='font-bold text-secondary hover:text-light-coffee' target='_blank'>{post?.title}</Link>
                    <span className='text-right'>{datetimeHelpers.formatDate(post?.createdAt)}</span>
                  </li>
                ))
              }
            </ul>
          </div>
        </section>
      </AdminLayout>
    </>
  )
}

export default DashboardPage